"""
Base Guardian interface and common types for Cerberus guardians.
"""

from abc import ABC, abstractmethod
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ThreatLevel(str, Enum):
    """Threat severity levels."""

    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ThreatReport(BaseModel):
    """Report generated by a guardian after analyzing input."""

    guardian_id: str = Field(..., description="Unique identifier of the guardian")
    guardian_type: str = Field(..., description="Type of guardian that generated this report")
    threat_level: ThreatLevel = Field(
        default=ThreatLevel.NONE, description="Assessed threat level"
    )
    confidence: float = Field(
        default=0.0, ge=0.0, le=1.0, description="Confidence score (0.0 to 1.0)"
    )
    threats_detected: list[str] = Field(
        default_factory=list, description="List of detected threat descriptions"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata from analysis"
    )
    should_block: bool = Field(default=False, description="Whether the input should be blocked")


class Guardian(ABC):
    """
    Abstract base class for all Cerberus guardians.

    Each guardian implements a different detection style to provide
    defense-in-depth against various attack vectors.
    """

    def __init__(self, guardian_id: str | None = None) -> None:
        """
        Initialize the guardian.

        Args:
            guardian_id: Optional unique identifier. If not provided,
                        one will be generated.
        """
        import uuid

        self._id = guardian_id or f"{self.guardian_type}-{uuid.uuid4().hex[:8]}"

    @property
    def id(self) -> str:
        """Return the unique identifier of this guardian."""
        return self._id

    @property
    @abstractmethod
    def guardian_type(self) -> str:
        """Return the type identifier for this guardian."""
        pass

    @abstractmethod
    def analyze(self, content: str, context: dict[str, Any] | None = None) -> ThreatReport:
        """
        Analyze content for potential threats.

        Args:
            content: The content to analyze (user input, prompt, etc.)
            context: Optional context information for analysis

        Returns:
            ThreatReport with analysis results
        """
        pass

    def _create_report(
        self,
        threat_level: ThreatLevel = ThreatLevel.NONE,
        confidence: float = 0.0,
        threats: list[str] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> ThreatReport:
        """Helper method to create a threat report."""
        threats = threats or []
        should_block = threat_level in (ThreatLevel.HIGH, ThreatLevel.CRITICAL)

        return ThreatReport(
            guardian_id=self.id,
            guardian_type=self.guardian_type,
            threat_level=threat_level,
            confidence=confidence,
            threats_detected=threats,
            metadata=metadata or {},
            should_block=should_block,
        )
